[package]
name = "apibara-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
prost = "0.11.0"
prost-types = "0.11.1"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
tonic = "0.8.0"
tracing = "0.1.36"

[build-dependencies]
tonic-build = "0.8.0"
